### ISSUE TITLE
[s2] Binary Update for Coverageparser to fix PHPUnit overall coverage issue

### ISSUE THREAD

**Issue by domitian** [Shippable/cexec#118]
1. Support issue https://github.com/Shippable/support/issues/2499 s2
2. 2.  We are calculating the total coverage by average of percentages of files, it will always distort the coverage percent because each file could have different number of lines. So if a file with less number of valid lines has very less percentage then it will distort overall for example. As created in https://github.com/Shippable/micro/issues/939

**Comment by ric03uec** [comment]
updated beta with latest binary

**Comment by domitian** [comment]
Beta verified, Please deploy in prod in next cycle.

**Comment by ric03uec** [comment]
this will be deployed to prod today 2100 PST

**Comment by ric03uec** [comment]
@domitian this is in prod now. can you please verify and close.

**Comment by domitian** [comment]
prod verified
