### ISSUE TITLE
no logs shown when cexec runs

### ISSUE THREAD

**Issue by ric03uec** [Shippable/cexec#37]
- https://github.com/Shippable/pm/issues/4997
- the only logs shown on `cexec` console when its running are 
```
Booting up CEXEC
Running CEXEC script
CEXEC has completed
```
- this just takes away all debugging capabilities out of it.

**Comment by rageshkrishna** [comment]
In "PROD" mode, exceptions and anything with "error" log level should still be visible in the container console. Boot failures, for example, would still get logged here like this:

![bad_mexec](https://cloud.githubusercontent.com/assets/1134972/12500871/408acdc8-c0dd-11e5-8c14-cbfd0d7e0daa.png)

What other output would you like to see logged here?

**Comment by ric03uec** [comment]
i guess i didn't realize that cexec logs were streaming in on the user console. this should be good.
closing
